#!/bin/sh
#
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

PROJECT_DIR=$(pwd)
SERVER_DIR=$PROJECT_DIR/server
CLIENT_DIR=$PROJECT_DIR/client

$PROJECT_DIR/add-licence-headers.sh

# Test the server side
cd $SERVER_DIR
npm run pre-commit

# Test the client side
#cd $PROJECT_DIR/client
#npm run test-no-browser
